### ISSUE TITLE
./ffmpeg.sh: line 16 error

### ISSUE THREAD

**Issue by MrJay84** [TheOpponent/mr-otcs#13]
Hello mate.

Hope you can help me out here. I'm setting this up on a small Ubuntu VM but I've run into a small issue when starting ./ffmpeg gives the error...

`root@Ubuntu20:/home/joe/mr-otcs-1.5.2# ./ffmpeg.sh
./ffmpeg.sh: line 16: ts: command not found`

Nginx is running with the RTMP module, stream key is working and paths are set correctly.

**Comment by TheOpponent** [comment]
`ts` is a component of `moreutils` that provides timestamps to console output. Install with:
```sudo apt-get update
sudp apt-get install moreutils```

**Comment by MrJay84** [comment]
Thanks for the quick reply. I've got the running python stage but I'm get
`libOMX_Core.so not found
libOmxCore.so not found`

These seem to be RasberryPi only, I'm attempting to run this in a x86 based Virtual Machine. Is that at all possible? If not I'll juts have to buy a pi lol.

**Comment by TheOpponent** [comment]
My own use case was for embedded hardware, so I wrote specialized instructions for Raspberry Pi for the wiki. For other platforms, follow typical instructions for compiling ffmpeg, using the ffmpeg-hls-pts-discontinuity-reclock fork instead.

**Comment by joelang1699** [comment]
Excellent. I now have it running properly. One last question Gong if I may. How did you get the currently paying file name to display down the left hand aid eof the screen on the Twitch stream?

**Comment by TheOpponent** [comment]
Those are burned into the video. I encode every video manually to include that information.

**Comment by TheOpponent** [comment]
Also, if your stream doesn't transition between videos properly, ensure you added the `--disable-librtmp` flag to your ffmpeg compilation.

**Comment by MrJay84** [comment]
I have noticed that the stream pauses very slightly between episodes along with the session timer resetting on Twitch. I did add that flag FFmeg before compiling. I'll try that again, I have a duplicate VM I keep for messing around with.
![Screenshot 2022-01-28 165539](https://user-images.githubusercontent.com/92555921/151588758-bf6ddafc-c1dc-4ff1-80d6-9e94395d926a.jpg)
h

**Comment by MrJay84** [comment]
Also I noticed that once the playlist is finished it stops broadcasting, how would I tell it to repeat the playlist?

**Comment by TheOpponent** [comment]
The playlist loops by default. If this doesn't happen, check the output for error messages.
