### ISSUE TITLE
Error running python script

### ISSUE THREAD

**Issue by Silvernox** [TheOpponent/mr-otcs#14]
When running the python script I keep getting this error message

[NULL @ 0x2996aa0] Failed to parse extradata
[h264_omx @ 0x29ab1c0] /opt/vc/lib/libopenmaxil.so not found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

Would you have any idea what could be wrong with this?

**Comment by TheOpponent** [comment]
This is an error with the encoding process. Ensure that your `gpu_mem` is set to 128 or greater.

**Comment by Silvernox** [comment]
Thanks. I have set this in /boot/config.txt to 256, and rebooted. Same error message is appearing.

**Comment by TheOpponent** [comment]
The [ffmpeg-hls-pts-discontinuity-reclock](https://github.com/jjustman/ffmpeg-hls-pts-discontinuity-reclock) compiling process likely failed. What compile flags were set when it was compiled?

**Comment by Silvernox** [comment]
cd ~ && git clone --depth 1 https://github.com/jjustman/ffmpeg-hls-pts-discontinuity-reclock.git \
  && cd ~/ffmpeg-hls-pts-discontinuity-reclock \
  && ./configure \
    --extra-cflags="-I/usr/local/include" \
    --extra-ldflags="-L/usr/local/lib" \
    --extra-libs="-lpthread -lm -latomic" \
    --arch=armel \
    --enable-gmp \
    --enable-gpl \
    --enable-libaom \
    --enable-libass \
    --enable-libdrm \
    --enable-libfdk-aac \
    --enable-libfreetype \
    --enable-libkvazaar \
    --enable-libmp3lame \
    --enable-libopencore-amrnb \
    --enable-libopencore-amrwb \
    --enable-libopus \
    --enable-librtmp \
    --enable-libsnappy \
    --enable-libsoxr \
    --enable-libssh \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libzimg \
    --enable-libwebp \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxml2 \
    --enable-mmal \
    --enable-nonfree \
    --enable-omx \
    --enable-omx-rpi \
    --enable-version3 \
    --target-os=linux \
    --enable-pthreads \
    --enable-openssl \
    --enable-hardcoded-tables \
  && make -j$(nproc) \
  && sudo make install

**Comment by TheOpponent** [comment]
If the entirety of `/opt/vc` is missing, it may be possible to restore the needed files by installing `libraspberrypi-bin` with `apt`.

Additionally, `--enable-librtmp` will need to be changed to `--disable-librtmp` as librtmp itself will not work with this project.

**Comment by Silvernox** [comment]
Still nothing there after an reinstalling libraspberrypi-bin, so I don’t know if it’s putting it somewhere else.

I think I’m going to scrap this and start from scratch again. I have Raspbian Bullseye on this now, the 64 bit version, would it be better to just get a copy of the lite version? Thanks!

**Comment by TheOpponent** [comment]
The instance running OTCS is based on Raspbian OS Lite Buster 32-bit. The only adjustment made prior to installation was to set `gpu_mem` to 256. Searching for similar errors to this issue returned reports of other users needing to reinstall the Raspberry Pi firmware package, so I believed it would have corrected it here. I have not tested other versions of Raspbian OS, but I believe there should be no issues with a clean installation of any recent version. Good luck.

**Comment by Silvernox** [comment]
The /opt/vc directory has been restored after running rpi-update.

This broadcom.video_encode, if im getting an error with this, does it point towards there being a problem during compile time for ffmpeg? Thanks.

Press [q] to stop, [?] for help
[NULL @ 0x39afaa0] Failed to parse extradata
[h264_omx @ 0x39c41c0] Using OMX.broadcom.video_encode
[h264_omx @ 0x39c41c0] OMX_GetHandle(OMX.broadcom.video_encode) failed: 800010
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or heig
Conversion failed!

**Comment by TheOpponent** [comment]
If you're still getting errors about metadata, it could be an issue with the video you're trying to transcode. What is the nature of the source video?

**Comment by Silvernox** [comment]
The video I'm testing with is a mkv file. I'll find some other formats and see if they're the same.

**Comment by TheOpponent** [comment]
This is due to the use of the `h264_omx` codec in Raspberry Pi OS Bullseye. To resolve this, the codec must be changed to `h264_v4l2m2m`. However, in version 1.x, this requires the script to be edited to use a newer version of ffmpeg alongside the RTMP encoder, which is the default configuration in version 2.0.
