### ISSUE TITLE
RTMP process ended unexpectedly

### ISSUE THREAD

**Issue by redhalo** [TheOpponent/mr-otcs#21]
I've attempted to make a docker container for mr-otcs to run on a Synology NAS and am getting the following errors looping forever that aren't clear as to the cause.

[Info] RTMP process started on 2023-10-21 17:24:02.933743.
[Play] 1. /videos/test.mkv - Length: 0:04:48.
[Info] 47:54:10 left before restart.
[Info] Encoding started on 2023-10-21 17:24:03.004853.
[Error] RTMP process ended unexpectedly on 2023-10-21 17:24:03.415517, exit code 1. Restarting stream.
[Error] Stream interrupted. Attempting to restart.

I realize that's out of the scope of your project, but was hoping you may have had some insight where to look to find what's happening to the stream.

**Comment by TheOpponent** [comment]
Try replacing lines 120-125 in main.py with this:
```python
try:
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
except subprocess.CalledProcessError as e:
    stdout, stderr = process.communicate()
    print(stderr.decode())
    print2("error",f"Encoder process ended unexpectedly on {datetime.datetime.now()}, exit code {e.returncode}.")
    return e.returncode
```
And change the ffmpeg command line in `RTMP_ARGUMENTS` from `-loglevel fatal` to `-loglevel error`. This should start printing stderr to console if it's not doing it now. I'm away from home until next week so I won't be able to examine this in detail until then.

**Comment by redhalo** [comment]
Thanks for the response and no worries. Unfortunately the changes don't give me any new info. I'm new to creating docker images so there may be something particular to my situation. I'm beginning to think that ffmpeg is attempting hardware transcoding and I may need to fiddle with docker on my end.

**Comment by redhalo** [comment]
Figured it out! Apparently nginx wasn't actually starting in the docker image and thus ffmpeg wasnt actually connecting. Sorry for the bother.
